import { AlbumTheme } from '@/types';

export const albumThemes: Record<string, AlbumTheme> = {
  // Original Albums
  debut: {
    id: 'debut',
    name: 'Taylor Swift',
    releaseYear: '2006',
    type: 'original',
    light: {
      primary: '#6C9A8B',
      secondary: '#8FB3A3',
      accent: '#F4E4BC',
      background: '#F8FAF8',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#8FB3A3',
      secondary: '#A8C4B8',
      accent: '#F4E4BC',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #6C9A8B 0%, #8FB3A3 100%)',
    coverImage: '/images/albums/debut.jpg',
    themeColor: '#6C9A8B',
  },
  fearless: {
    id: 'fearless',
    name: 'Fearless',
    releaseYear: '2008',
    type: 'original',
    light: {
      primary: '#D4AF37',
      secondary: '#F4D03F',
      accent: '#FEF9E7',
      background: '#FEFCE8',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#F4D03F',
      secondary: '#F7DC6F',
      accent: '#FEF9E7',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #D4AF37 0%, #F4D03F 100%)',
    coverImage: '/images/albums/fearless.jpg',
    themeColor: '#D4AF37',
  },
  'speak-now': {
    id: 'speak-now',
    name: 'Speak Now',
    releaseYear: '2010',
    type: 'original',
    light: {
      primary: '#A349A4',
      secondary: '#C084FC',
      accent: '#F3E8FF',
      background: '#FAF5FF',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#C084FC',
      secondary: '#D8B4FE',
      accent: '#F3E8FF',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #A349A4 0%, #C084FC 100%)',
    coverImage: '/images/albums/speak-now.jpg',
    themeColor: '#A349A4',
  },
  red: {
    id: 'red',
    name: 'Red',
    releaseYear: '2012',
    type: 'original',
    light: {
      primary: '#B22222',
      secondary: '#DC2626',
      accent: '#FEE2E2',
      background: '#FEF2F2',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#FEE2E2',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #B22222 0%, #DC2626 100%)',
    coverImage: '/images/albums/red.jpg',
    themeColor: '#B22222',
  },
  '1989': {
    id: '1989',
    name: '1989',
    releaseYear: '2014',
    type: 'original',
    light: {
      primary: '#87CEEB',
      secondary: '#A5D8FF',
      accent: '#E0F2FE',
      background: '#F0F9FF',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#A5D8FF',
      secondary: '#BAE6FD',
      accent: '#E0F2FE',
      background: '#0C4A6E',
      surface: '#0E7490',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #87CEEB 0%, #A5D8FF 100%)',
    coverImage: '/images/albums/1989.jpg',
    themeColor: '#87CEEB',
  },
  reputation: {
    id: 'reputation',
    name: 'Reputation',
    releaseYear: '2017',
    type: 'original',
    light: {
      primary: '#333333',
      secondary: '#4A5568',
      accent: '#F59E0B',
      background: '#F7FAFC',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#F59E0B',
      secondary: '#FBBF24',
      accent: '#333333',
      background: '#000000',
      surface: '#1A202C',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #333333 0%, #4A5568 100%)',
    coverImage: '/images/albums/reputation.jpg',
    themeColor: '#333333',
  },
  lover: {
    id: 'lover',
    name: 'Lover',
    releaseYear: '2019',
    type: 'original',
    light: {
      primary: '#FFB6C1',
      secondary: '#FBB6CE',
      accent: '#FDF2F8',
      background: '#FDF2F8',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#FBB6CE',
      secondary: '#F9A8D4',
      accent: '#FDF2F8',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #FFB6C1 0%, #FBB6CE 100%)',
    coverImage: '/images/albums/lover.jpg',
    themeColor: '#FFB6C1',
  },
  folklore: {
    id: 'folklore',
    name: 'Folklore',
    releaseYear: '2020',
    type: 'original',
    light: {
      primary: '#C0C0C0',
      secondary: '#D1D5DB',
      accent: '#F3F4F6',
      background: '#F9FAFB',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#D1D5DB',
      secondary: '#E5E7EB',
      accent: '#F3F4F6',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #C0C0C0 0%, #D1D5DB 100%)',
    coverImage: '/images/albums/folklore.jpg',
    themeColor: '#C0C0C0',
  },
  evermore: {
    id: 'evermore',
    name: 'Evermore',
    releaseYear: '2020',
    type: 'original',
    light: {
      primary: '#A0522D',
      secondary: '#CD853F',
      accent: '#FEF3C7',
      background: '#FEFCE8',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#CD853F',
      secondary: '#DEB887',
      accent: '#FEF3C7',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #A0522D 0%, #CD853F 100%)',
    coverImage: '/images/albums/evermore.jpg',
    themeColor: '#A0522D',
  },
  
  // Taylor's Versions
  'fearless-tv': {
    id: 'fearless-tv',
    name: 'Fearless (Taylor\'s Version)',
    releaseYear: '2021',
    type: 'taylors-version',
    light: {
      primary: '#FFD700',
      secondary: '#FFED4E',
      accent: '#FEF9E7',
      background: '#FEFCE8',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#FFED4E',
      secondary: '#FFF176',
      accent: '#FEF9E7',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #FFD700 0%, #FFED4E 100%)',
    coverImage: '/images/albums/fearless-tv.jpg',
    themeColor: '#FFD700',
  },
  'red-tv': {
    id: 'red-tv',
    name: 'Red (Taylor\'s Version)',
    releaseYear: '2021',
    type: 'taylors-version',
    light: {
      primary: '#8B0000',
      secondary: '#B22222',
      accent: '#FEE2E2',
      background: '#FEF2F2',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#B22222',
      secondary: '#DC2626',
      accent: '#FEE2E2',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #8B0000 0%, #B22222 100%)',
    coverImage: '/images/albums/red-tv.jpg',
    themeColor: '#8B0000',
  },
  midnights: {
    id: 'midnights',
    name: 'Midnights',
    releaseYear: '2022',
    type: 'original',
    light: {
      primary: '#191970',
      secondary: '#2E2E8B',
      accent: '#F59E0B',
      background: '#F8FAFC',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#F59E0B',
      secondary: '#FBBF24',
      accent: '#191970',
      background: '#0F172A',
      surface: '#1E293B',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #191970 0%, #2E2E8B 100%)',
    coverImage: '/images/albums/midnights.jpg',
    themeColor: '#191970',
  },
  'speak-now-tv': {
    id: 'speak-now-tv',
    name: 'Speak Now (Taylor\'s Version)',
    releaseYear: '2023',
    type: 'taylors-version',
    light: {
      primary: '#800080',
      secondary: '#9932CC',
      accent: '#F3E8FF',
      background: '#FAF5FF',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#9932CC',
      secondary: '#B366FF',
      accent: '#F3E8FF',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #800080 0%, #9932CC 100%)',
    coverImage: '/images/albums/speak-now-tv.jpg',
    themeColor: '#800080',
  },
  '1989-tv': {
    id: '1989-tv',
    name: '1989 (Taylor\'s Version)',
    releaseYear: '2023',
    type: 'taylors-version',
    light: {
      primary: '#1E90FF',
      secondary: '#4FC3F7',
      accent: '#E0F2FE',
      background: '#F0F9FF',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#4FC3F7',
      secondary: '#81D4FA',
      accent: '#E0F2FE',
      background: '#0C4A6E',
      surface: '#0E7490',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #1E90FF 0%, #4FC3F7 100%)',
    coverImage: '/images/albums/1989-tv.jpg',
    themeColor: '#1E90FF',
  },
  
  // New Albums
  'tortured-poets': {
    id: 'tortured-poets',
    name: 'The Tortured Poets Department',
    releaseYear: '2024',
    type: 'original',
    light: {
      primary: '#708090',
      secondary: '#8F9CA8',
      accent: '#F5F5F5',
      background: '#FAFAFA',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#8F9CA8',
      secondary: '#A8B5C1',
      accent: '#F5F5F5',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #708090 0%, #8F9CA8 100%)',
    coverImage: '/images/albums/tortured-poets.jpg',
    themeColor: '#708090',
  },
  'life-of-showgirl': {
    id: 'life-of-showgirl',
    name: 'The Life of a Showgirl',
    releaseYear: '2025',
    type: 'upcoming',
    light: {
      primary: '#FF8C00',
      secondary: '#FFA500',
      accent: '#20B2AA',
      background: '#FFF8F0',
      surface: '#ffffff',
      text: '#2D3748',
      textSecondary: '#718096',
    },
    dark: {
      primary: '#FFA500',
      secondary: '#FFB84D',
      accent: '#20B2AA',
      background: '#1A1A1A',
      surface: '#2D2D2D',
      text: '#F7FAFC',
      textSecondary: '#A0AEC0',
    },
    gradient: 'linear-gradient(135deg, #FF8C00 0%, #20B2AA 100%)',
    coverImage: '/images/albums/life-of-showgirl.jpg',
    themeColor: '#FF8C00',
  },
};

// Chronological order array for proper album ordering
export const albumOrder: Array<keyof typeof albumThemes> = [
  'debut',
  'fearless', 
  'speak-now',
  'red',
  '1989',
  'reputation',
  'lover',
  'folklore',
  'evermore',
  'fearless-tv',
  'red-tv',
  'midnights',
  'speak-now-tv',
  '1989-tv',
  'tortured-poets',
  'life-of-showgirl'
];

export const defaultTheme = albumThemes.midnights;